language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
 - python -m unittest
  
after_success:
  - bash < (curl -s https://codecov.io/bash)

branches:
  only:
    - master
