language: python
python:
  - "3.6"

install:
  - pip install codecov
  - pip install -r requirements.txt

script:
 - python -m unittest
  
after_success:
  - coverage run test_gerry.py
  
branches:
  only:
    - master
